### ISSUE TITLE
Compatibility with Angular 8.0.0

### ISSUE THREAD

**Issue by sw-dev-code** [RLoris/lib-ng-opengallery#10]
Is there any way to run this package with Angular 8.0.0?

I've tried with all versions of package but always getting the same error:

```
../node_modules/ng-opengallery/lib/components/simple-gallery/simple-gallery.component.d.ts:16:9 - error TS1086: An accessor cannot be declared in an ambient context.

16     get autoplay(): boolean;
           ~~~~~~~~
../node_modules/ng-opengallery/lib/ng-opengallery.component.d.ts:12:9 - error TS1086: An accessor cannot be declared in an ambient context.

12     set datasource(v: Media[]);
           ~~~~~~~~~~
../node_modules/ng-opengallery/lib/ng-opengallery.component.d.ts:15:9 - error TS1086: An accessor cannot be declared in an ambient context.

15     set config(v: Config);
           ~~~~~~
../node_modules/ng-opengallery/lib/ng-opengallery.component.d.ts:16:9 - error TS1086: An accessor cannot be declared in an ambient context.

16     get config(): Config;
```

**Comment by RLoris** [comment]
Hello, this seems like a typescript version error, take a look at this : https://stackoverflow.com/questions/60092642/ts1086-an-accessor-cannot-be-declared-in-ambient-context

**Comment by sw-dev-code** [comment]
@RLoris Thanks, that solved the issues. 

But, now the production version is not working as I'm getting the following error:

```
main-es2015.bb2aab5f416a4b7a8b72.js:1 ERROR NullInjectorError: StaticInjectorError(a)[S -> e]: 
  StaticInjectorError(Platform: core)[S -> e]: 
    NullInjectorError: No provider for e!
```

When I remove the `ng-opengallery` from code that error dissapears.

**Comment by RLoris** [comment]
Did you import ng-opengallery in your app.module.ts like this : 
```
import { NgOpengalleryModule } from 'ng-opengallery'; // -> HERE 

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    NgOpengalleryModule // -> HERE
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

**Comment by sw-dev-code** [comment]
Yes I did, exactly in the same way you described but still getting the error. 
I was able to run the production without optimization in order to get more meaningful error log.

Here it is:

```
main-es2015.eeed9d29444d47a21802.js:37649 ERROR Error: Uncaught (in promise): NullInjectorError: StaticInjectorError(AppModule)[SimpleGalleryComponent -> NgOpengalleryService]: 
  StaticInjectorError(Platform: core)[SimpleGalleryComponent -> NgOpengalleryService]: 
    NullInjectorError: No provider for NgOpengalleryService!
NullInjectorError: StaticInjectorError(AppModule)[SimpleGalleryComponent -> NgOpengalleryService]: 
  StaticInjectorError(Platform: core)[SimpleGalleryComponent -> NgOpengalleryService]: 
    NullInjectorError: No provider for NgOpengalleryService! 
```

**Comment by RLoris** [comment]
Ok thanks, can you show me your app.module.ts ? And the template file (.html) where the gallery is used, I will try to replicate this error on my side

**Comment by sw-dev-code** [comment]
Below are the parts of the code from the files in which I'm using the gallery. Pages module is inside app module.

**app.module.ts**
```
import { NgOpengalleryModule } from 'ng-opengallery';

@NgModule({
  declarations: [AppComponent],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    HttpClientModule,
    AppRoutingModule,
    LeafletModule,
    NgOpengalleryModule,
    ....
```

**pages.module.ts**
```
import { NgOpengalleryModule } from 'ng-opengallery';

@NgModule({
  imports: [
    PagesRoutingModule,
    ThemeModule,
    ....,
    NgOpengalleryModule,
    ReactiveFormsModule,
  ],
```


**home.component.html**
```
              <ng-opengallery
                [datasource]='this.imageData'
                [config]='this.config'>
              </ng-opengallery>
```

**Comment by RLoris** [comment]
Hello, I have managed to make it work in debug with ng serve but as soon as I try to build for production, typescript errors appears because of version mismatch and changes between the newer version and angular 8

**Comment by sw-dev-code** [comment]
I have the same issue. Maybe you can put the versions of Angular/TypeScript supported and tested for future work.

**Comment by RLoris** [comment]
Will do, I updated the angular version of the library to get latest improvements of angular, if you really need it, you could update your angular version to 9 ? 

PS: in the readme of the repository the version used to generate the library was already written ^^

**Comment by sw-dev-code** [comment]
I saw it, but I thought it was able to support Angular 8. Anyway, thank you so much for the help. Closing this issue.
