### ISSUE TITLE
MediaViewerComponent does not open if I select the same image twice

### ISSUE THREAD

**Issue by ccarcione** [RLoris/lib-ng-opengallery#13]
when I try to open the same image for the second time, MediaViewerComponent is not shown.

![image](https://user-images.githubusercontent.com/11087896/126008020-f8265807-8412-4870-acb6-d8fcf61b583f.png)

I tried both by cloning the repository and with the lib npm.
the strange fact is that everything seems to work in the demo.

**Comment by RLoris** [comment]
Hi, I'm currently busy on other projects, can you show me a video or gif of your problem and the code you are using ? It will be easier for me to help you and debug

**Comment by ccarcione** [comment]
hi, thanks for the help! the problem can be reproduced from your repository. here is the useful gif to reproduce the problem:

![Animation](https://user-images.githubusercontent.com/11087896/126045178-78d9bc76-5ae1-4b8e-a255-cd2b0c0a574d.gif)

I use the library in this component--> https://gitlab.com/projects-experimenta/caprezzo-digitale/-/tree/29-lavori-galleria-immagini/public-client/src/app/component/galleria
you can also find the project on github --> https://github.com/ccarcione/caprezzo-digitale/tree/master/public-client/src/app/component/galleria

here is the link to the development environment of the project (go to the "galleria foto" menu item) --> https://caprezzodigitale.master.experimenta.cloud/

**Comment by RLoris** [comment]
Hello again, this should be fixed now if you update through npm to v0.0.6, can you confirm please ?

**Comment by ccarcione** [comment]
great! everything works perfectly! tested on your repository and in my project.

thank you so much for your timely support !!

**Comment by RLoris** [comment]
Great, I'm closing this issue since it's resolved, good luck with your project
