### ISSUE TITLE
push media dynamically

### ISSUE THREAD

**Issue by elham-sedighi** [RLoris/lib-ng-opengallery#2]
hi again
since i,m getting my video and images media urls separately from server i have to push them in Media array as the response comes from the server.
but for example when i push second item after first item, i have still one media in gallery view.(although media array has two members ). i need to add medias dynamically when ever I needed to.
thanks

**Comment by RLoris** [comment]
Great catch, I will try to update this tomorrow with observable, trigger an event data changed for example, I will keep you up to date

**Comment by RLoris** [comment]
Should be fixed now @elibushehri can you confirm ?

**Comment by elham-sedighi** [comment]
@RLoris Yeah that's ok, Perfect work. Good Luck
