### ISSUE TITLE
auto play video 

### ISSUE THREAD

**Issue by elham-sedighi** [RLoris/lib-ng-opengallery#3]
hi
is it possible to add another option to config? say "enableAutoPlay" to stop videos from being auto played. also i think you should consider pausing or stopping video after user clicks on video again to watch it on viewer right after it had been played in slider(out of viewer).
thanks again

**Comment by RLoris** [comment]
I will add this tomorrow, thanks for the suggestion, great idea !

**Comment by RLoris** [comment]
You should be good to go now, check and tell me, I have pushed changes to npm @elibushehri

**Comment by elham-sedighi** [comment]
@RLoris Great Job! fixed, thanks alot
