### ISSUE TITLE
Multiple Gallerys

### ISSUE THREAD

**Issue by GregorHub** [RLoris/lib-ng-opengallery#4]
Is it possible to use multiple gallerys with different datasources at the same time? 

i want to use the gallery like this:

    <ng-opengallery  [datasource]="this.set1"    ></ng-opengallery>
    <ng-opengallery  [datasource]="this.set2"    ></ng-opengallery>

But when i click on an image and then close the bigger view and then click on another image i get the folowing error:

![image](https://user-images.githubusercontent.com/47955133/106393465-8555d980-63f7-11eb-9ae4-786c4b789560.png)

when i change the code to :

```
<ng-opengallery  [datasource]="this.set1"    ></ng-opengallery>
<ng-opengallery  [datasource]="this.set1"    ></ng-opengallery>
```

the gallerys work perfektly fine!

**Comment by RLoris** [comment]
Hi, I'm going to take a look at this on my free time and let you know !

**Comment by RLoris** [comment]
The bug should be fixed @GregorHub I pushed changes to npm registry, can you confirm ?

**Comment by GregorHub** [comment]
Yes, i can confirm that the bug is fixed, therefore i will close this issue.
Thank u very much!!!
