### ISSUE TITLE
Remove Effects on Images 

### ISSUE THREAD

**Issue by MahmoudTarekAli** [RLoris/lib-ng-opengallery#5]
How can I remove the effects (animation) on image when I slide to between images in carousel mode

**Comment by RLoris** [comment]
Hello there, I will add a property in the config to disable the animation and use your own class, stay tuned !

**Comment by RLoris** [comment]
Effects are now disable by default, you should be able to use your own class in the config (config.effectClass = 'yourownclass') if you want. Is it working for you ?
