### ISSUE TITLE
Is it possible to remove the play icon on the modal when the auto play property is disabled ?  

### ISSUE THREAD

**Issue by Tomekske** [RLoris/lib-ng-opengallery#7]

**Comment by RLoris** [comment]
Hey, the autoplay property acts in the gallery not in the viewer, autoplay means when a media like a video enters the viewport it automatically plays, the diaporama has nothing to do with autoplay, I could add a property to disable the diaporama in the viewer if it's useful to you ?

**Comment by Tomekske** [comment]
Yeah, that's what I had in mind. Sorry for the misunderstanding

**Comment by RLoris** [comment]
You can now remove the diaporama button by specifying the diaporama duration to 0 in the config (config.diaporamaDuration = 0), is it working for you ?

**Comment by Tomekske** [comment]
Works like a charm!
