### ISSUE TITLE
Is it possible to add a property for a picture to fill the screen ?

### ISSUE THREAD

**Issue by Tomekske** [RLoris/lib-ng-opengallery#8]

**Comment by RLoris** [comment]
Hello there, you mean in the modal viewer ?

**Comment by Tomekske** [comment]
Yeah, I mean in the modal viewer. I think it would be a nice option to have, so people can decide for them selves which option they prefer

**Comment by RLoris** [comment]
config.viewerFullsize allows you to specify a media to fill the screen or keep a reduced size, there is also a button in the modal to toggle bewteen reduced and fill, is this ok for you now ?

**Comment by Tomekske** [comment]
Works like a charm!
